[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "xxx"
client_id = "xxx"
client_secret = "xxx"
server_metadata_url = "https://example.com/.well-known/openid-configuration"
client_kwargs = { "prompt" = "login" }
